### ISSUE TITLE
It's a virus.

### ISSUE THREAD

**Issue by InFuzzz** [Yours-Jarvis/Astaroth-Spammer#1]
This program is infected with Gen:Variant.Spider.1 virus ... 

**DO NOT DOWNLOAD THIS PROGRAM!!!**

![image](https://user-images.githubusercontent.com/75752848/179360115-93cefdc9-ad66-41c4-82f5-f18bcb9890e3.png)
![image](https://user-images.githubusercontent.com/75752848/179360121-80e4f323-7087-4cac-8bcf-baf53fd98e79.png)

**Comment by Yours-Jarvis** [comment]
its not contain from virus brother in the windows(system) some file are called viruses i.e batch, bat & Trojan but it is not contain from virus if u use this program u need to off win.defender
